### ISSUE TITLE
Ionic setup

### ISSUE THREAD

**Issue by ohadgk** [BastienL/GPSDetector#6]
can you please explain how to setup this plugin in the ionic framwork?
I cant understand where to put the files.

**Comment by BastienL** [comment]
Hi Muffasa,

Unfortunately, I'm not familiar with the Ionic framework so I'm afraid I won't be able to help you. As my plugin is designed as any PhoneGap plugin, maybe a common tutorial about how to embed a PhoneGap plugin into an Ionic app will help you?
